import type { AppData, ExploitationData, BudgetData, StaffRow, WorkforceRow, MovementRow, MedicalCare } from './types/budget';

const INITIAL_EXPLOITATION: ExploitationData = {
  operatingData: [
    { id: 'op1', category: 'r_op_imp', subcategory: 'r_sub_cae', volume: { kgs: 0, m3: 0, litre: 0 }, value: { cif: 0, fob: 0, marchande: 0 }, occFees: 0, dpdVerification: 0, result: 0 },
    { id: 'op2', category: 'r_op_imp', subcategory: 'r_sub_caa', volume: { kgs: 0, m3: 0, litre: 0 }, value: { cif: 0, fob: 0, marchande: 0 }, occFees: 0, dpdVerification: 0, result: 0 },
    { id: 'op3', category: 'r_op_exp', subcategory: '', volume: { kgs: 0, m3: 0, litre: 0 }, value: { cif: 0, fob: 0, marchande: 0 }, occFees: 0, dpdVerification: 0, result: 0 },
    { id: 'op4', category: 'r_op_prod_loc', subcategory: '', volume: { kgs: 0, m3: 0, litre: 0 }, value: { cif: 0, fob: 0, marchande: 0 }, occFees: 0, dpdVerification: 0, result: 0 },
    { id: 'op5', category: 'r_op_trafic', subcategory: '', volume: { kgs: 0, m3: 0, litre: 0 }, value: { cif: 0, fob: 0, marchande: 0 }, occFees: 0, dpdVerification: 0, result: 0 },
    { id: 'op6', category: 'r_op_trans_loc', subcategory: '', volume: { kgs: 0, m3: 0, litre: 0 }, value: { cif: 0, fob: 0, marchande: 0 }, occFees: 0, dpdVerification: 0, result: 0 },
  ],
  failures: [
    { id: 'f1', name: 'r_fail_constats', count: '' },
    { id: 'f2', name: 'r_fail_prev', count: '' },
  ],
  labAnalysis: [],
  metrology: [
    { id: 'mt1', name: 'r_met_metro', count: 0 },
    { id: 'mt2', name: 'r_met_other', count: 0 },
  ],
  technicalControl: [
    { id: 'tc1', name: 'r_tc_lifting', count: 0 },
    { id: 'tc2', name: 'r_tc_pressure', count: 0 },
    { id: 'tc3', name: 'r_tc_elec', count: 0 },
    { id: 'tc4', name: 'r_tc_other', count: 0 },
  ],
};

const INITIAL_BUDGET: BudgetData = {
  production: [
    { id: 'bp1', label: 'r_bud_exp', forecast: 0, achievement: 0 },
    { id: 'bp2', label: 'r_bud_imp', forecast: 0, achievement: 0 },
    { id: 'bp3', label: 'r_bud_prod_loc', forecast: 0, achievement: 0 },
    { id: 'bp4', label: 'r_bud_trafic', forecast: 0, achievement: 0 },
    { id: 'bp5', label: 'r_bud_trans_loc', forecast: 0, achievement: 0 },
    { id: 'bp6', label: 'r_bud_lab', forecast: 0, achievement: 0 },
    { id: 'bp7', label: 'Damages', forecast: 0, achievement: 0 },
    { id: 'bp8', label: 'r_bud_metro', forecast: 0, achievement: 0 },
    { id: 'bp9', label: 'r_bud_tech_ctrl', forecast: 0, achievement: 0 },
  ],
  charges: [
    { id: 'bc1', label: 'r_bud_60', forecast: 0, achievement: 0 },
    { id: 'bc2', label: 'r_bud_61', forecast: 0, achievement: 0 },
    { id: 'bc3', label: 'r_bud_62', forecast: 0, achievement: 0 },
    { id: 'bc4', label: 'r_bud_63', forecast: 0, achievement: 0 },
    { id: 'bc5', label: 'r_bud_64', forecast: 0, achievement: 0 },
    { id: 'bc6', label: 'r_bud_65', forecast: 0, achievement: 0 },
    { id: 'bc7', label: 'r_bud_66', forecast: 0, achievement: 0 },
    { id: 'bc8', label: 'r_bud_67', forecast: 0, achievement: 0 },
    { id: 'bc9', label: 'r_bud_83', forecast: 0, achievement: 0 },
  ],
  treasuryReceipts: [
    { id: 'tr1', label: 'r_tr_init', forecast: 0, achievement: 0 },
    { id: 'tr2', label: 'r_tr_fact', forecast: 0, achievement: 0 },
    { id: 'tr3', label: 'r_tr_tva', forecast: 0, achievement: 0 },
    { id: 'tr4', label: 'r_tr_debt', forecast: 0, achievement: 0 },
    { id: 'tr5', label: 'r_tr_trans', forecast: 0, achievement: 0 },
    { id: 'tr6', label: 'r_tr_other', forecast: 0, achievement: 0 },
  ],
  treasuryDisbursements: [
    { id: 'td1', label: 'r_bud_60', forecast: 0, achievement: 0 },
    { id: 'td2', label: 'r_bud_61', forecast: 0, achievement: 0 },
    { id: 'td3', label: 'r_bud_62', forecast: 0, achievement: 0 },
    { id: 'td4', label: 'r_bud_63', forecast: 0, achievement: 0 },
    { id: 'td5', label: 'r_bud_64', forecast: 0, achievement: 0 },
    { id: 'td6', label: 'r_bud_65', forecast: 0, achievement: 0 },
    { id: 'td7', label: 'r_bud_66', forecast: 0, achievement: 0 },
    { id: 'td8', label: 'r_bud_67', forecast: 0, achievement: 0 },
    { id: 'td9', label: 'r_bud_83', forecast: 0, achievement: 0 },
    { id: 'td10', label: 'r_td_invest', forecast: 0, achievement: 0 },
    { id: 'td11', label: 'r_td_trans', forecast: 0, achievement: 0 },
    { id: 'td12', label: 'r_td_other', forecast: 0, achievement: 0 },
  ],
};

const INITIAL_STAFF: StaffRow[] = [
  { id: 'p1', category: 'r_p_cat_dir', grade: 'r_gr_dir', male: 0, female: 0 },
  { id: 'p2', category: 'r_p_cat_dir', grade: 'r_gr_da', male: 0, female: 0 },
  { id: 'p3', category: 'r_p_cat_dir', grade: 'r_gr_sd', male: 0, female: 0 },
  { id: 'p4', category: 'r_p_cat_senior', grade: 'r_gr_fpp', male: 0, female: 0 },
  { id: 'p5', category: 'r_p_cat_senior', grade: 'r_gr_fp', male: 0, female: 0 },
  { id: 'p6', category: 'r_p_cat_sub', grade: 'r_gr_cs3', male: 0, female: 0 },
  { id: 'p7', category: 'r_p_cat_sub', grade: 'r_gr_cs2', male: 0, female: 0 },
  { id: 'p8', category: 'r_p_cat_sub', grade: 'r_gr_cs1', male: 0, female: 0 },
  { id: 'p9', category: 'r_p_cat_sup', grade: 'r_gr_m3', male: 0, female: 0 },
  { id: 'p10', category: 'r_p_cat_sup', grade: 'r_gr_m2', male: 0, female: 0 },
  { id: 'p11', category: 'r_p_cat_sup', grade: 'r_gr_m1', male: 0, female: 0 },
  { id: 'p12', category: 'r_p_cat_ech', grade: 'r_gr_c9', male: 0, female: 0 },
  { id: 'p13', category: 'r_p_cat_ech', grade: 'r_gr_c8', male: 0, female: 0 },
  { id: 'p14', category: 'r_p_cat_ech', grade: 'r_gr_c7', male: 0, female: 0 },
  { id: 'p15', category: 'r_p_cat_ech', grade: 'r_gr_c6', male: 0, female: 0 },
];

const INITIAL_WORKFORCE: WorkforceRow[] = [
  { level: 'r_w_univ', DIR: 0, DA: 0, SD: 0, FPP: 0, FP: 0, CS3: 0, CS2: 0, CS1: 0, M3: 0, M2: 0, M1: 0, C9: 0, C8: 0, C7: 0, C6: 0 },
  { level: 'r_w_sec', DIR: 0, DA: 0, SD: 0, FPP: 0, FP: 0, CS3: 0, CS2: 0, CS1: 0, M3: 0, M2: 0, M1: 0, C9: 0, C8: 0, C7: 0, C6: 0 },
  { level: 'r_w_prim', DIR: 0, DA: 0, SD: 0, FPP: 0, FP: 0, CS3: 0, CS2: 0, CS1: 0, M3: 0, M2: 0, M1: 0, C9: 0, C8: 0, C7: 0, C6: 0 },
];

const INITIAL_MOVEMENTS: MovementRow[] = [
  { id: 'm01', type: 'r_mov_01', count: 0, observation: '' },
  { id: 'm02', type: 'r_mov_02', count: 0, observation: '' },
  { id: 'm03', type: 'r_mov_03', count: 0, observation: '' },
  { id: 'm04', type: 'r_mov_04', count: 0, observation: '' },
  { id: 'm05', type: 'r_mov_05', count: 0, observation: '' },
  { id: 'm06', type: 'r_mov_06', count: 0, observation: '' },
  { id: 'm07', type: 'r_mov_07', count: 0, observation: '' },
  { id: 'm08', type: 'r_mov_08', count: 0, observation: '' },
  { id: 'm09', type: 'r_mov_09', count: 0, observation: '' },
  { id: 'm10', type: 'r_mov_10', count: 0, observation: '' },
  { id: 'm11', type: 'r_mov_11', count: 0, observation: '' },
  { id: 'm12', type: 'r_mov_12', count: 0, observation: '' },
  { id: 'm13', type: 'r_mov_13', count: 0, observation: '' },
  { id: 'm14', type: 'r_mov_14', count: 0, observation: '' },
  { id: 'm15', type: 'r_mov_15', count: 0, observation: '' },
  { id: 'm16', type: 'r_mov_16', count: 0, observation: '' },
  { id: 'm17', type: 'r_mov_17', count: 0, observation: '' },
  { id: 'm18', type: 'r_mov_18', count: 0, observation: '' },
  { id: 'm19', type: 'r_mov_19', count: 0, observation: '' },
];

const INITIAL_MEDICAL_CARE: MedicalCare[] = [
  { category: 'r_med_hosp', usd: 0, cdf: 0 },
  { category: 'r_med_pharm', usd: 0, cdf: 0 },
  { category: 'r_med_lab', usd: 0, cdf: 0 },
  { category: 'r_med_ref', usd: 0, cdf: 0 },
];

export const INITIAL_DATA: AppData = {
  staff: INITIAL_STAFF,
  managementCount: 0,
  salaryMassCDF: 0,
  movements: INITIAL_MOVEMENTS,
  workforce: INITIAL_WORKFORCE,
  serviceMissions: {
    performed: { type: 'performed', count: 0, cost: 0 },
    received: { type: 'received', count: 0, cost: 0 },
  },
  medicalCare: INITIAL_MEDICAL_CARE,
  transfersKinshasa: [],
  transfersAbroad: [],
  missionCosts: {
    inside: { usd: 0, cdf: 0 },
    abroad: { usd: 0, cdf: 0 },
  },
  divers: [
    { category: 'r_div_fuel', usd: 0, cdf: 0 },
    { category: 'r_div_off', usd: 0, cdf: 0 },
    { category: 'r_div_maint', usd: 0, cdf: 0 },
    { category: 'r_div_recep', usd: 0, cdf: 0 },
    { category: 'r_div_other', usd: 0, cdf: 0 },
  ],
  exploitation: INITIAL_EXPLOITATION,
  budget: INITIAL_BUDGET
};

export const TRANSLATIONS: Record<string, string> = {
  // Personnel Categories
  'r_p_cat_dir': 'Management Staff',
  'r_p_cat_senior': 'Senior Staff',
  'r_p_cat_sub': 'Subordinate Staff',
  'r_p_cat_sup': 'Supervisory Staff',
  'r_p_cat_ech': 'Execution Staff',
  
  // Grades
  'r_gr_dir': 'DIR',
  'r_gr_da': 'DA',
  'r_gr_sd': 'SD',
  'r_gr_fpp': 'FPP',
  'r_gr_fp': 'FP',
  'r_gr_cs3': 'CS3',
  'r_gr_cs2': 'CS2',
  'r_gr_cs1': 'CS1',
  'r_gr_m3': 'M3',
  'r_gr_m2': 'M2',
  'r_gr_m1': 'M1',
  'r_gr_c9': 'C9',
  'r_gr_c8': 'C8',
  'r_gr_c7': 'C7',
  'r_gr_c6': 'C6',

  // Movements
  'r_mov_01': 'Hiring (Engagement)',
  'r_mov_02': 'Dismissal/Termination',
  'r_mov_03': 'Resignation',
  'r_mov_04': 'Desertion',
  'r_mov_05': 'Placement on Leave',
  'r_mov_06': 'Reintegration',
  'r_mov_07': 'Commissioning',
  'r_mov_08': 'Secondment',
  'r_mov_09': 'Physical Restoration Leave',
  'r_mov_10': 'Circumstantial Leave',
  'r_mov_11': 'Medical Rest',
  'r_mov_12': 'Transfer (Mutation)',
  'r_mov_13': 'Interim',
  'r_mov_14': 'Retirees',
  'r_mov_15': 'Moving Leave',
  'r_mov_16': 'Deceased',
  'r_mov_17': 'MONTH HEADCOUNT',
  'r_mov_18': 'SUPPORT STAFF',
  'r_mov_19': 'OPERATIONAL STAFF',

  // Workforce Levels
  'r_w_univ': 'University',
  'r_w_sec': 'Secondary',
  'r_w_prim': 'Primary/Other',

  // Medical
  'r_med_hosp': 'Approved Hospitals',
  'r_med_pharm': 'Pharmacies',
  'r_med_lab': 'Laboratories',
  'r_med_ref': 'Refunds',

  // Divers
  'r_div_fuel': 'Fuel/Lubricants',
  'r_div_off': 'Office Supplies',
  'r_div_maint': 'Maintenance',
  'r_div_recep': 'Reception Costs',
  'r_div_other': 'Miscellaneous',

  // Operating Data
  'r_op_imp': 'IMPORTATION',
  'r_op_exp': 'EXPORTATION',
  'r_op_prod_loc': 'LOCAL PRODUCTION',
  'r_op_trafic': 'BORDER TRAFFIC',
  'r_op_trans_loc': 'LOCAL TRANSACTION',
  'r_sub_cae': 'CAE',
  'r_sub_caa': 'CAA',

  // Failures
  'r_fail_constats': 'Findings',
  'r_fail_prev': 'Prevention',

  // Metrology
  'r_met_metro': 'Metrology',
  'r_met_other': 'Other Services',

  // Technical Control
  'r_tc_lifting': 'Lifting Equipment',
  'r_tc_pressure': 'Pressure Equipment',
  'r_tc_elec': 'Electrical Equipment',
  'r_tc_other': 'Other Services',

  // Budget Production
  'r_bud_exp': 'EXPORTATION',
  'r_bud_imp': 'IMPORTATION',
  'r_bud_prod_loc': 'LOCAL PRODUCTION',
  'r_bud_trafic': 'BORDER TRAFFIC',
  'r_bud_trans_loc': 'LOCAL TRANSACTION',
  'r_bud_lab': 'LAB ANALYSIS',
  'r_bud_avaries': 'FAILURES/DAMAGES',
  'r_bud_metro': 'METROLOGY',
  'r_bud_tech_ctrl': 'TECHNICAL CONTROL',

  // Budget Charges
  'r_bud_60': '60. Purchases & Stock',
  'r_bud_61': '61. Transport',
  'r_bud_62': '62. External Services A',
  'r_bud_63': '63. External Services B',
  'r_bud_64': '64. Taxes',
  'r_bud_65': '65. Other Charges',
  'r_bud_66': '66. Personnel Charges',
  'r_bud_67': '67. Financial Charges',
  'r_bud_83': '83. Non-activity Charges',

  // Treasury Receipts
  'r_tr_init': 'Initial Balance',
  'r_tr_fact': 'Invoicing/Receipts',
  'r_tr_tva': 'VAT',
  'r_tr_debt': 'Matured Debts',
  'r_tr_trans': 'Received Transfers',
  'r_tr_other': 'Other Receipts',

  // Treasury Disbursements
  'r_td_invest': 'Investments',
  'r_td_trans': 'Made Transfers',
  'r_td_other': 'Other Disbursements',

  // Common Labels
  'sec_personnel': 'Personnel Management',
  'col_category': 'Category',
  'col_grade': 'Grade',
  'col_male': 'Male',
  'col_female': 'Female',
  'col_total': 'Total',
  'lbl_management_count': 'Management Count (Auto)',
  'lbl_salary_mass': 'Salary Mass (CDF)',
  'sec_workforce': 'Workforce by Education',
  'Level': 'Education Level',
  'sec_movement': 'Personnel Movement',
  'Movement': 'Movement Type',
  'Effectif': 'Count',
  'Observation': 'Observation',
  'Missions': 'Service Missions',
  'Performed': 'Performed',
  'Received': 'Received',
  'Medical Care': 'Medical Care',
  'Transfers Kinshasa': 'Transfers - Kinshasa',
  'Transfers Abroad': 'Transfers - Abroad',
  'Entity': 'Entity',
  'Agents': 'Agents',
  'Retirees': 'Retirees',
  'Wives': 'Spouses',
  'Children': 'Children',
  'Divers': 'Miscellaneous',
  'Inside': 'Domestic',
  'Abroad': 'International',
  'sec_operating': 'Operating Data',
  'Product': 'Product',
  'Volume': 'Volume',
  'Value': 'Value',
  'Fees & Result': 'Fees & Results',
  'Failures': 'Failures',
  'Type': 'Type',
  'Count': 'Count',
  'Description': 'Description',
  'Metrology': 'Metrology',
  'TechControl': 'Technical Control',
  'sec_budget_production': 'Production Budget',
  'sec_budget_charges': 'Operating Charges',
  'sec_treasury_receipts': 'Treasury Receipts',
  'sec_treasury_disbursements': 'Treasury Disbursements',
  'Designation': 'Designation',
  'Forecast': 'Forecast',
  'Achievements': 'Achievements',
  'RealRate': 'Achievement Rate',
  'sec_dashboard': 'Key Performance Indicators',
  'Dashboard_Indicator': 'Indicator',
  'Dashboard_Formula': 'Formula',
  'Dashboard_Value': 'Value',
  'dashboard_lbl_total_workforce': 'Total Workforce',
  'dashboard_fml_total_workforce': 'Sum of personnel',
  'dashboard_lbl_va': 'Added Value (V.A.)',
  'dashboard_fml_va': 'Production - Charges(60-65)',
  'dashboard_lbl_coeff': 'Operating Coefficient',
  'dashboard_fml_coeff': 'Production / Total Charges',
  'dashboard_lbl_ebe': 'EBITDA (EBE)',
  'dashboard_fml_ebe': 'V.A. - Charge(66)',
  'dashboard_lbl_re': 'Operating Result (R.E.)',
  'dashboard_fml_re': 'EBE - Charge(67)',
  'dashboard_lbl_encours': 'Outstanding Receivables',
  'dashboard_fml_encours': 'Production - Net Receipts',
  'dashboard_lbl_recovery': 'Recovery Rate',
  'dashboard_fml_recovery': '(Receipts / Production) × 100',
  'dashboard_lbl_productivity': 'Productivity',
  'dashboard_fml_productivity': 'Production / Workforce',
  'dashboard_lbl_avg_cost': 'Average Cost per Employee',
  'dashboard_fml_avg_cost': 'Charge(66) / Workforce',
  'dashboard_lbl_supervision': 'Supervision Ratio',
  'dashboard_fml_supervision': 'Workforce / Management',
  'dashboard_lbl_avg_salary': 'Average Salary',
  'dashboard_fml_avg_salary': 'Salary Mass / Workforce',
};
